[package]
name = "macroquad-viewplane-camera"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Dynamic and easy rendering of a 2D plane using Macroquad's camera system."
repository = "https://github.com/iMilchshake/macroquad-viewplane-camera"
categories = ["rendering::engine"]
exclude = ["/.github"]

[dependencies]
macroquad = "0.4"
